version: '3'

services:
  jx-payments-manning:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/manning/jx-payments-manning
    ports:
      - "8080:8080"
    networks:
      - main

networks:
  main:
