apiVersion: v1
kind: Service
metadata:
  name: jx-payments-service
spec:
  selector:
    app: jx-payments-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jx-payments-deployment
  labels:
    app: jx-payments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jx-payments-app
  template:
    metadata:
      labels:
        app: jx-payments-app
    spec:
      containers:
      - image: andymert/jx-payments
        name: jx-payments
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: jx-payments
          protocol: TCP
        resources:
          limits:
            memory: "512Mi"
            cpu: "1.0"
          requests:
            memory: "256Mi"
            cpu: "0.5"
